/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Test/community`; params?: Router.UnknownInputParams; } | { pathname: `/Test/library`; params?: Router.UnknownInputParams; } | { pathname: `/Test/login`; params?: Router.UnknownInputParams; } | { pathname: `/Test/player`; params?: Router.UnknownInputParams; } | { pathname: `/Test/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Test/upload`; params?: Router.UnknownInputParams; } | { pathname: `/Test/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/components/BookCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/CastCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ContinueCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/FormField`; params?: Router.UnknownInputParams; } | { pathname: `/components/GradientButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/MiniPlayer`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/Screen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Test/community`; params?: Router.UnknownOutputParams; } | { pathname: `/Test/library`; params?: Router.UnknownOutputParams; } | { pathname: `/Test/login`; params?: Router.UnknownOutputParams; } | { pathname: `/Test/player`; params?: Router.UnknownOutputParams; } | { pathname: `/Test/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Test/upload`; params?: Router.UnknownOutputParams; } | { pathname: `/Test/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BookCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CastCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ContinueCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FormField`; params?: Router.UnknownOutputParams; } | { pathname: `/components/GradientButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MiniPlayer`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProgressBar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Screen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/theme${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Test/community${`?${string}` | `#${string}` | ''}` | `/Test/library${`?${string}` | `#${string}` | ''}` | `/Test/login${`?${string}` | `#${string}` | ''}` | `/Test/player${`?${string}` | `#${string}` | ''}` | `/Test/profile${`?${string}` | `#${string}` | ''}` | `/Test/upload${`?${string}` | `#${string}` | ''}` | `/Test/welcome${`?${string}` | `#${string}` | ''}` | `/components/BookCard${`?${string}` | `#${string}` | ''}` | `/components/CastCard${`?${string}` | `#${string}` | ''}` | `/components/ContinueCard${`?${string}` | `#${string}` | ''}` | `/components/FormField${`?${string}` | `#${string}` | ''}` | `/components/GradientButton${`?${string}` | `#${string}` | ''}` | `/components/MiniPlayer${`?${string}` | `#${string}` | ''}` | `/components/ProgressBar${`?${string}` | `#${string}` | ''}` | `/components/Screen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Test/community`; params?: Router.UnknownInputParams; } | { pathname: `/Test/library`; params?: Router.UnknownInputParams; } | { pathname: `/Test/login`; params?: Router.UnknownInputParams; } | { pathname: `/Test/player`; params?: Router.UnknownInputParams; } | { pathname: `/Test/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Test/upload`; params?: Router.UnknownInputParams; } | { pathname: `/Test/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/components/BookCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/CastCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ContinueCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/FormField`; params?: Router.UnknownInputParams; } | { pathname: `/components/GradientButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/MiniPlayer`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/Screen`; params?: Router.UnknownInputParams; };
    }
  }
}
